//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 23.07.2015 23:20:13
namespace Majestic
{
    
    /// <summary>
    /// There are no comments for RepositoryEntities in the schema.
    /// </summary>
    public partial class RepositoryEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new RepositoryEntities object using the connection string found in the 'RepositoryEntities' section of the application configuration file.
        /// </summary>
        public RepositoryEntities() : 
                base("name=RepositoryEntities", "RepositoryEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new RepositoryEntities object.
        /// </summary>
        public RepositoryEntities(string connectionString) : 
                base(connectionString, "RepositoryEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new RepositoryEntities object.
        /// </summary>
        public RepositoryEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "RepositoryEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Contracts in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Contracts> Contracts
        {
            get
            {
                if ((this._Contracts == null))
                {
                    this._Contracts = base.CreateQuery<Contracts>("[Contracts]");
                }
                return this._Contracts;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Contracts> _Contracts;
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Roles> Roles
        {
            get
            {
                if ((this._Roles == null))
                {
                    this._Roles = base.CreateQuery<Roles>("[Roles]");
                }
                return this._Roles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Roles> _Roles;
        /// <summary>
        /// There are no comments for UserRoles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserRoles> UserRoles
        {
            get
            {
                if ((this._UserRoles == null))
                {
                    this._UserRoles = base.CreateQuery<UserRoles>("[UserRoles]");
                }
                return this._UserRoles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserRoles> _UserRoles;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// There are no comments for Contracts in the schema.
        /// </summary>
        public void AddToContracts(Contracts contracts)
        {
            base.AddObject("Contracts", contracts);
        }
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        public void AddToRoles(Roles roles)
        {
            base.AddObject("Roles", roles);
        }
        /// <summary>
        /// There are no comments for UserRoles in the schema.
        /// </summary>
        public void AddToUserRoles(UserRoles userRoles)
        {
            base.AddObject("UserRoles", userRoles);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    }
    /// <summary>
    /// There are no comments for RepositoryModel.Contracts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RepositoryModel", Name="Contracts")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Contracts : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Contracts object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="userId">Initial value of UserId.</param>
        public static Contracts CreateContracts(int id, int userId)
        {
            Contracts contracts = new Contracts();
            contracts.ID = id;
            contracts.UserId = userId;
            return contracts;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private global::System.Nullable<bool> _Status;
        partial void OnStatusChanging(global::System.Nullable<bool> value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
    }
    /// <summary>
    /// There are no comments for RepositoryModel.Roles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RepositoryModel", Name="Roles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Roles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Roles object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Roles CreateRoles(int id)
        {
            Roles roles = new Roles();
            roles.Id = id;
            return roles;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for RepositoryModel.UserRoles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RepositoryModel", Name="UserRoles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserRoles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UserRoles object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="roleId">Initial value of RoleId.</param>
        /// <param name="userId">Initial value of UserId.</param>
        public static UserRoles CreateUserRoles(int id, int roleId, int userId)
        {
            UserRoles userRoles = new UserRoles();
            userRoles.ID = id;
            userRoles.RoleId = roleId;
            userRoles.UserId = userId;
            return userRoles;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property RoleId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this.OnRoleIdChanging(value);
                this.ReportPropertyChanging("RoleId");
                this._RoleId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RoleId");
                this.OnRoleIdChanged();
            }
        }
        private int _RoleId;
        partial void OnRoleIdChanging(int value);
        partial void OnRoleIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
    }
    /// <summary>
    /// There are no comments for RepositoryModel.Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RepositoryModel", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Users CreateUsers(int id)
        {
            Users users = new Users();
            users.ID = id;
            return users;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UserLogin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLogin
        {
            get
            {
                return this._UserLogin;
            }
            set
            {
                this.OnUserLoginChanging(value);
                this.ReportPropertyChanging("UserLogin");
                this._UserLogin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserLogin");
                this.OnUserLoginChanged();
            }
        }
        private string _UserLogin;
        partial void OnUserLoginChanging(string value);
        partial void OnUserLoginChanged();
        /// <summary>
        /// There are no comments for Property UserEmail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail
        {
            get
            {
                return this._UserEmail;
            }
            set
            {
                this.OnUserEmailChanging(value);
                this.ReportPropertyChanging("UserEmail");
                this._UserEmail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserEmail");
                this.OnUserEmailChanged();
            }
        }
        private string _UserEmail;
        partial void OnUserEmailChanging(string value);
        partial void OnUserEmailChanged();
        /// <summary>
        /// There are no comments for Property UserPsw in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPsw
        {
            get
            {
                return this._UserPsw;
            }
            set
            {
                this.OnUserPswChanging(value);
                this.ReportPropertyChanging("UserPsw");
                this._UserPsw = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserPsw");
                this.OnUserPswChanged();
            }
        }
        private string _UserPsw;
        partial void OnUserPswChanging(string value);
        partial void OnUserPswChanged();
    }
}
